### ISSUE TITLE
openroad should write it's commands into the log

### ISSUE THREAD

**Issue by stefanottili** [The-OpenROAD-Project/OpenROAD#3539]
### Description

Revisiting a year old log files, it would have been very helpful to have the CMD's that were issued to be in the log file.

### Suggested Solution

write CMD's into the log file

**Comment by maliberty** [comment]
To implement: tcl's trace can be used to call into the logger

**Comment by Iyury1** [comment]
I'd to work on this.

**Comment by maliberty** [comment]
Great!

**Comment by Iyury1** [comment]
This is taking me a bit longer than I expected. Commands are entered directly to the embedded TCL interpreter, so the logger would need to be invoked within the interpreter. I have considered two approaches to do this.

One way would be to create a custom alias for the TCL eval command using Tcl_CreateAlias(). This way we can assign our own C++ function to this alias for logging the command name, then call the original eval so the command is still executed. A potential problem is that eval might be called by the interpreter in more cases then with our custom commands, so we may need to check that we are only logging the commands we want. We would need to maintain a list of all commands we want to log and search this list before logging any command from our new function. 

Another way would be to create a new TCL function that is called before any of our custom commands. Perhaps there is a way to prepend this function to each TCL commands upon initialization. I am not sure how this would work yet, but maybe we could change sta/etc/TclEncode.tcl to include this.

I don't know how feasible either approach is, but the first one sounds simpler so I plan to try that first. If I can actually get the arguments of eval to be logged, then I will see if there is extra output that we don't need.

**Comment by QuantamHD** [comment]
Just want to jump in that the other thing we could try is to add this functionality to TCL. It wouldn't immediately be available to users on standard distros, but the pre-built binaries could take advantage of it.

https://core.tcl-lang.org/tcl/wiki?name=Index

**Comment by gadfort** [comment]
@QuantamHD the tcl_trace functionality is there. I briefly looked at this (adding a trace to utl) and it's possible to get the commands, but depending on the entry method (gui vs non-gui, cmd arg file vs command line) changes how the tracing worked so I didn't go any further.  I don't think there is anything to add to Tcl, I think the solution is to fix how we interface with Tcl to make this possible.

**Comment by Iyury1** [comment]
I am too busy to work on this right now unfortunately.

I need to prioritize some other projects for a few months. If this still hasn't been resolved by then I can take another look at it.

**Comment by dav77227** [comment]
Hello @Iyury1 @gadfort @stefanottili @QuantamHD @maliberty, I would like to work on this issue. Do you know if anyone is already working on it?

**Comment by gadfort** [comment]
@dav77227 I don't know about the others, but I am not working on this. Good luck.

**Comment by stefanottili** [comment]
To add features to this request: every “long running” command should report how long it took to run it.
The goal would be to be able to easily compare log files from different runs. 
E.g.
vimdiff dir[12]/log
or
grep runtime dir2/log > dir2/runtime
diff dir[12]/runtime

**Comment by gadfort** [comment]
@stefanottili that feels like a separate feature request. Plus that would be better if it can be implemented in the C code so it is available to the python interface too.

**Comment by stefanottili** [comment]
@gadfort you're right, separate feature request https://github.com/The-OpenROAD-Project/OpenROAD/issues/5003

**Comment by dav77227** [comment]
Hello. Currently, I have implemented the following solution, which I would like to discuss before creating a PR. @maliberty @QuantamHD @gadfort @stefanottili could you please provide your feedback on this matter?
The concept of the solution is the following:
1. The TCL script passed to the OpenROAD is substituted with a tracing script that adds tracing functionality and calls the `source` command with the original TCL script. The script substitution is done in the OpenROAD main function. 
I'm attaching the `2_2_floorplan_io.log` log files with and without my changes for your review.
[2_2_floorplan_io_before.log](https://github.com/The-OpenROAD-Project/OpenROAD/files/15428604/2_2_floorplan_io_before.log)
[2_2_floorplan_io_after.log](https://github.com/The-OpenROAD-Project/OpenROAD/files/15428603/2_2_floorplan_io_after.log)

**Comment by maliberty** [comment]
Does your solution work if the user is simply typing commands at the interactive prompt and not executing a script?

**Comment by dav77227** [comment]
The current tracing functionality is called through TCL script, thus the solution works only when working with the script and not from the interactive mode.

**Comment by maliberty** [comment]
Is it possible to setup the tracing on the interpreter so it doesn't matter what the input source is?

**Comment by gadfort** [comment]
@maliberty yes it's possible. I think I still have the code I put together earlier, it might be possible to avoid the depth issue I ran into previously by using the commands registered in sta (similar to what we do in the GUI) to create a list of commands to echo back.

**Comment by dav77227** [comment]
There are log_begin and log_end commands in OpenROAD used to initiate logging during an interactive session. I tried to use them, but somehow it didn't work: the file is created, but nothing is written (I have called different commands to get the result into a log file). Is there something incorrect ?
Here are the command sequence that I have used: 
```
openroad> log_begin myfile.log
openroad> read_lef path_to_OpenROAD/flow/platforms/nangate45/lef/NangateOpenCellLibrary.tech.lef
openroad> read_verilog path_to_OpenROAD/flow/results/nangate45/gcd/base/1_synth.v
openroad> report_units
openroad> write_db file.db
openroad> log_end
openroad> exit
```

**Comment by maliberty** [comment]
log_begin is an sta command and won't work across all of OR.  Its more relevant in the context of standalone sta.

**Comment by gadfort** [comment]
@dav77227 yes, that is correct.

**Comment by dav77227** [comment]
Greetings. I've implemented a solution using the `Tcl_CreateObjTrace` function. It performs trace for prompt mode and in case of script execution. However, a lot of things can be printed in the case of batch mode: a procedure can call other procedures in their body, and this can reach a certain level recursively. So I'd like to clarify which commands/procedures are best to print to have a balanced output. One option is to print only top level commands, however this will imply that if the underlying implementation of the top level command is changed over the time it will not be noticeable from the logs, on the other hand if we print all levels then, we will have pretty big logging only for a single top level command. 
I think it's best to decide on a real example. So the `io_placement_random.tcl` script is the following:

```
source $::env(SCRIPTS_DIR)/load.tcl
load_design 2_1_floorplan.odb 1_synth.sdc

if {[info exists ::env(FLOORPLAN_DEF)]} {
    puts "Skipping IO placement as DEF file was used to initialize floorplan."
} else {
  if {[info exists ::env(IO_CONSTRAINTS)]} {
    source $::env(IO_CONSTRAINTS)
  }
  place_pins -hor_layer $::env(IO_PLACER_H) \
           -ver_layer $::env(IO_PLACER_V) \
           -random \
           {*}$::env(PLACE_PINS_ARGS)
}

write_db $::env(RESULTS_DIR)/2_2_floorplan_io.odb
```
@maliberty @QuantamHD @gadfort @stefanottili could you please specify what should be printed for this exact script?

**Comment by gadfort** [comment]
You could use this chunk of code : https://github.com/The-OpenROAD-Project/OpenROAD/blob/ad54bbe88b561d1c30451d8a3c85ad11c1692905/src/gui/src/tclCmdInputWidget.cpp#L392
To determine what command names are registered in openroad

**Comment by RayChang987** [comment]
Hi, I’m wondering if this issue is still present or if it has already been addressed!

**Comment by maliberty** [comment]
Still present

**Comment by RayChang987** [comment]
Currently working on it!
I used the chunk of code that @gadfort mentioned and logged the registered commands from the `sta::cmd_args` array by tracing on the interpreter (`Tcl_CreateTrace` in `tclAppInit`). It seems to work fine in both interactive mode and script execution.

Here’s an example log from running `src/dbSta/test/find_clks1.tcl`.
```
[CMD] suppress_message ODB 127 
[CMD] suppress_message ODB 134
[CMD] suppress_message TAP 100
[CMD] suppress_message TAP 101
[CMD] suppress_message PAR 6
[CMD] suppress_message PAR 38
[CMD] suppress_message ORD 30
[CMD] read_lef Nangate45/Nangate45.lef
[INFO ODB-0227] LEF file: Nangate45/Nangate45.lef, created 22 layers, 27 vias, 135 library cells
[CMD] read_lef pad.lef
[INFO ODB-0227] LEF file: pad.lef, created 1 library cells
[CMD] read_liberty Nangate45/Nangate45_typ.lib
[CMD] read_liberty Nangate45/Nangate45_typ.lib
[CMD] read_liberty pad.lib
[CMD] read_liberty pad.lib
[CMD] read_def find_clks1.def
[INFO ODB-0128] Design: top
[INFO ODB-0130]     Created 3 pins.
[INFO ODB-0131]     Created 4 components and 22 component-terminals.
[INFO ODB-0132]     Created 2 special nets and 6 connections.
[INFO ODB-0133]     Created 6 nets and 10 connections.
[CMD] create_clock -name clk -period 10 clk1
[CMD] create_clock -name clk -period 10 clk1
```
However, commands in namespaces would not be logged in the example above (e.g., `sta::find_all_clk_nets`). Logging commands from namespaces like `sta` could cause recursive logging.
For example:
`read_lef` could trigger `sta::parse_key_args` and `sta::check_argc_eq1` internally.

**Comment by maliberty** [comment]
In general we discourage the use of commands in namespaces.  However we have been a bit sloppy in a few areas (eg gui) and its hard to make wrappers for all of odb.  I think we could find solutions to this if everything else is working for the global namespace.  Would you make a draft PR so I can try what you have and get more insight?

**Comment by kirobaghdad** [comment]
I want to work on this issue! @maliberty

**Comment by sparsh-karna** [comment]
Hi @maliberty , I'd like to work on this issue. Is it still open for contributions? I've reviewed the existing PR #9704 and the discussion, I have a plan to address the core filtering problem by whitelisting registered OR commands at startup rather than trying to exclude noise. Let me know if I can pick this up.

**Comment by maliberty** [comment]
You are welcome to give it a try.  How do you plan to generate the whitelist?

**Comment by sparsh-karna** [comment]
> You are welcome to give it a try. How do you plan to generate the whitelist?

Thanks! My plan is to generate the whitelist by calling `Tcl_Eval(interp, "info commands")` right after `ord::initOpenRoad()` completes, at that point all OR-specific commands are registered in the interpreter. I'll capture that list into an `std::unordered_set<std::string>` and pass it as `clientData` to `Tcl_CreateObjTrace`. The callback then does a simple set lookup and only logs commands that are in the whitelist.

One question: should I include commands from namespaces like `sta::` and `odb::`, or only global namespace commands? The earlier discussion suggested namespaces can cause recursive logging, but I want to confirm what scope you'd expect.

**Comment by kris70lesgo** [comment]
Hi @maliberty ,
I noticed PR #10686 has been waiting since the last review on June 30 and still has unresolved feedback regarding duplicated command logging and preserving the original Tcl command structure.
I'd be interested in working on this issue if the current PR is no longer being actively developed. Would you prefer that contributors help improve the existing implementation, or would you be open to a new implementation that addresses the review comments?
Thanks!

**Comment by maliberty** [comment]
Its very tricky to do this right.  You are welcome to give it a go but please read the issues with previous attempts.
